# Generated by Django 5.2.5 on 2026-08-24 14:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("severity", models.CharField(default="HIGH", max_length=20)),
                ("repeat_interval_minutes", models.PositiveIntegerField(default=30)),
                ("escalation_minutes", models.PositiveIntegerField(default=60)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "EMAIL"),
                            ("WECHAT", "WECHAT"),
                            ("DINGTALK", "DINGTALK"),
                            ("WEBHOOK", "WEBHOOK"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("config", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel_type", "name"), name="uniq_channel_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phase", models.CharField(max_length=20)),
                ("recipient_key", models.CharField(default="default", max_length=255)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_summary", models.CharField(blank=True, max_length=500)),
                ("sent_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="alerts.notificationchannel"
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "phase", "channel", "recipient_key"),
                        name="uniq_notification_phase",
                    )
                ],
            },
        ),
    ]
