# Generated by Django 5.2.5 on 2026-08-24 14:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "access_mode",
                    models.CharField(
                        choices=[("PUBLIC", "公开"), ("TOKEN", "令牌")],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(blank=True, max_length=128)),
                ("theme_color", models.CharField(default="#0c6c79", max_length=16)),
                ("is_enabled", models.BooleanField(default=True)),
                ("businesses", models.ManyToManyField(blank=True, to="businesses.businesssystem")),
                ("monitors", models.ManyToManyField(blank=True, to="monitors.monitor")),
            ],
        ),
    ]
