# Generated by Django 5.2.5 on 2026-08-24 14:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "monitor_type",
                    models.CharField(
                        choices=[
                            ("HTTP", "HTTP"),
                            ("API", "API"),
                            ("TCP", "TCP"),
                            ("PING", "PING"),
                            ("DNS", "DNS"),
                            ("SSL", "SSL"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target", models.CharField(max_length=2048)),
                ("interval_seconds", models.PositiveIntegerField(default=60)),
                ("timeout_seconds", models.PositiveIntegerField(default=10)),
                ("failure_threshold", models.PositiveIntegerField(default=3)),
                ("recovery_threshold", models.PositiveIntegerField(default=2)),
                ("warning_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "next_run_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="businesses.businesssystem",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="businesses.tag")),
            ],
        ),
        migrations.CreateModel(
            name="BusinessChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chains",
                        to="businesses.businesssystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChainNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("is_critical", models.BooleanField(default=True)),
                ("position", models.JSONField(default=dict)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="monitors.businesschain",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monitors.monitor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitorResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("execution_key", models.CharField(max_length=128, unique=True)),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField()),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField()),
                ("success", models.BooleanField()),
                ("latency_ms", models.FloatField(null=True)),
                ("status_code", models.IntegerField(null=True)),
                ("packet_loss", models.FloatField(null=True)),
                ("ssl_days_remaining", models.IntegerField(null=True)),
                ("error_type", models.CharField(max_length=40, null=True)),
                ("error_summary", models.CharField(max_length=500, null=True)),
                ("metrics", models.JSONField(default=dict)),
                ("assertions", models.JSONField(default=list)),
                ("detail", models.JSONField(default=dict)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="monitors.monitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StateTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("UP", "UP"),
                            ("DEGRADED", "DEGRADED"),
                            ("DOWN", "DOWN"),
                            ("PAUSED", "PAUSED"),
                            ("MAINTENANCE", "MAINTENANCE"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("UP", "UP"),
                            ("DEGRADED", "DEGRADED"),
                            ("DOWN", "DOWN"),
                            ("PAUSED", "PAUSED"),
                            ("MAINTENANCE", "MAINTENANCE"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="monitors.monitor",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="monitors.monitorresult"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChainEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="monitors.businesschain",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="monitors.chainnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="monitors.chainnode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain", "source", "target"), name="uniq_chain_edge"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitorState",
            fields=[
                (
                    "monitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="state",
                        serialize=False,
                        to="monitors.monitor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("UP", "UP"),
                            ("DEGRADED", "DEGRADED"),
                            ("DOWN", "DOWN"),
                            ("PAUSED", "PAUSED"),
                            ("MAINTENANCE", "MAINTENANCE"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("consecutive_successes", models.PositiveIntegerField(default=0)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "last_result",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitors.monitorresult",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["is_enabled", "next_run_at"], name="monitors_mo_is_enab_02070a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monitor",
            constraint=models.CheckConstraint(
                condition=models.Q(("timeout_seconds__lt", models.F("interval_seconds"))),
                name="timeout_lt_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="chainnode",
            constraint=models.UniqueConstraint(
                fields=("chain", "monitor"), name="uniq_chain_monitor"
            ),
        ),
        migrations.AddIndex(
            model_name="monitorresult",
            index=models.Index(
                fields=["monitor", "-checked_at"], name="monitors_mo_monitor_08d72a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statetransition",
            index=models.Index(
                fields=["monitor", "-occurred_at"], name="monitors_st_monitor_58479e_idx"
            ),
        ),
    ]
