# Generated by Django 5.2.5 on 2026-08-24 14:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("monitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("timezone", models.CharField(default="Asia/Shanghai", max_length=64)),
                ("recurrence", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("continue_probing", models.BooleanField(default=True)),
                ("suppress_notifications", models.BooleanField(default=True)),
                ("exclude_from_sla", models.BooleanField(default=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("businesses", models.ManyToManyField(blank=True, to="businesses.businesssystem")),
                ("monitors", models.ManyToManyField(blank=True, to="monitors.monitor")),
            ],
        ),
    ]
