# Generated by Django 5.2.5 on 2026-08-24 14:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("monitors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("ACKNOWLEDGED", "ACKNOWLEDGED"),
                            ("PROCESSING", "PROCESSING"),
                            ("RECOVERED", "RECOVERED"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "CRITICAL"),
                            ("HIGH", "HIGH"),
                            ("MEDIUM", "MEDIUM"),
                            ("LOW", "LOW"),
                        ],
                        default="HIGH",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("acknowledged_at", models.DateTimeField(null=True)),
                ("recovered_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                ("root_cause", models.TextField(blank=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="monitors.monitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["status", "-opened_at"], name="incidents_i_status_73e437_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["NEW", "ACKNOWLEDGED", "PROCESSING"])),
                fields=("monitor",),
                name="uniq_open_incident",
            ),
        ),
    ]
