export type FieldType = 'text'|'textarea'|'number'|'boolean'|'select'|'relation'|'json'|'datetime'
export interface FieldConfig { key:string; label:string; type?:FieldType; required?:boolean; options?:string[]; endpoint?:string; multiple?:boolean; default?:unknown; placeholder?:string; help?:string }
export interface ResourceConfig { title:string; endpoint:string; columns:FieldConfig[]; fields?:FieldConfig[]; readonly?:boolean; actions?:string[] }
const f=(key:string,label:string,extra:Partial<FieldConfig>={}):FieldConfig=>({key,label,type:'text',...extra})
export const resourceConfigs:Record<string,ResourceConfig>={
  businesses:{title:'业务系统',endpoint:'business-systems',columns:[f('name','名称'),f('code','编码'),f('level','等级'),f('environment','环境'),f('is_enabled','启用',{type:'boolean'})],fields:[f('name','名称',{required:true}),f('code','编码',{required:true}),f('description','描述',{type:'textarea'}),f('group','业务分组',{type:'relation',endpoint:'business-groups'}),f('department','所属部门',{type:'relation',endpoint:'departments'}),f('owner','负责人',{type:'relation',endpoint:'users'}),f('level','重要等级',{type:'select',options:['CORE','IMPORTANT','NORMAL'],default:'NORMAL'}),f('environment','环境',{default:'production'}),f('sla_target','SLA目标',{type:'number',default:99.9}),f('service_schedule','服务时间',{type:'json',default:{}}),f('tags','标签',{type:'relation',endpoint:'tags',multiple:true}),f('is_enabled','启用',{type:'boolean',default:true}),f('is_archived','归档',{type:'boolean',default:false})]},
  'business-groups':{title:'业务分组',endpoint:'business-groups',columns:[f('name','名称'),f('parent','父级'),f('sort_order','排序')],fields:[f('name','名称',{required:true}),f('parent','父级',{type:'relation',endpoint:'business-groups'}),f('sort_order','排序',{type:'number',default:0})]},
  tags:{title:'标签管理',endpoint:'tags',columns:[f('name','名称'),f('color','颜色')],fields:[f('name','名称',{required:true}),f('color','颜色',{default:'#409EFF'})]},
  monitors:{title:'探测任务',endpoint:'monitors',columns:[f('name','名称'),f('monitor_type','类型'),f('target','目标'),f('current_status','当前状态'),f('service_available','服务可用',{type:'boolean'}),f('last_checked_at','最近探测',{type:'datetime'}),f('is_enabled','启用',{type:'boolean'}),f('next_run_at','下次执行',{type:'datetime'})],actions:['test'],fields:[f('business','业务系统',{type:'relation',endpoint:'business-systems',required:true,help:'选择该探测任务所属的业务系统'}),f('name','名称',{required:true,placeholder:'例如：订单 API 健康检查'}),f('monitor_type','探测类型',{type:'select',options:['HTTP','API','TCP','PING','DNS','SSL','MSSQL','POSTGRESQL','MYSQL','MONGODB'],required:true,default:'HTTP',help:'支持网络、接口及主流数据库服务可用性探测'}),f('target','目标',{required:true}),f('interval_seconds','周期（秒）',{type:'number',default:60,help:'两次自动探测之间的时间，必须大于超时时间'}),f('timeout_seconds','超时（秒）',{type:'number',default:10,help:'单次连接与响应等待上限'}),f('failure_threshold','连续失败阈值',{type:'number',default:3,help:'首次真实失败会立即告警，该值用于状态升级为故障'}),f('recovery_threshold','连续恢复阈值',{type:'number',default:2,help:'连续成功达到该次数后确认恢复'}),f('warning_latency_ms','延迟阈值(ms)',{type:'number',placeholder:'例如：1000',help:'可选；超过该响应时间时标记为降级'}),f('config','高级配置',{type:'json',default:{}}),f('tags','标签',{type:'relation',endpoint:'tags',multiple:true}),f('is_enabled','启用',{type:'boolean',default:true})]},
  'monitor-results':{title:'探测结果',endpoint:'monitor-results',readonly:true,columns:[f('monitor','探测任务'),f('success','成功',{type:'boolean'}),f('latency_ms','响应时间(ms)'),f('status_code','状态码'),f('error_type','错误类型'),f('checked_at','探测时间',{type:'datetime'})]},
  chains:{title:'业务链路',endpoint:'business-chains',columns:[f('name','名称'),f('business','业务系统'),f('is_enabled','启用',{type:'boolean'})],fields:[f('business','业务系统',{type:'relation',endpoint:'business-systems',required:true}),f('name','名称',{required:true}),f('is_enabled','启用',{type:'boolean',default:true})]},
  incidents:{title:'故障事件',endpoint:'incidents',readonly:true,actions:['acknowledge','close'],columns:[f('number','事件编号'),f('title','标题'),f('severity','级别'),f('status','状态'),f('monitor','探测任务'),f('opened_at','发现时间',{type:'datetime'})]},
  rules:{title:'告警规则',endpoint:'alert-rules',columns:[f('name','名称'),f('severity','级别'),f('repeat_interval_minutes','重复间隔'),f('escalation_minutes','升级时间'),f('is_enabled','启用',{type:'boolean'})],fields:[f('name','名称',{required:true}),f('severity','级别',{type:'select',options:['CRITICAL','HIGH','MEDIUM','LOW'],default:'HIGH'}),f('repeat_interval_minutes','重复间隔(分钟)',{type:'number',default:30}),f('escalation_minutes','升级时间(分钟)',{type:'number',default:60}),f('is_enabled','启用',{type:'boolean',default:true})]},
  channels:{title:'通知渠道',endpoint:'notification-channels',columns:[f('name','名称'),f('channel_type','渠道类型'),f('is_enabled','启用',{type:'boolean'})],actions:['test-channel'],fields:[f('name','名称',{required:true}),f('channel_type','渠道类型',{type:'select',options:['EMAIL','WECHAT','DINGTALK','WEBHOOK'],required:true}),f('config','渠道配置',{type:'json',default:{}}),f('is_enabled','启用',{type:'boolean',default:true})]},
  notifications:{title:'发送记录',endpoint:'notification-logs',readonly:true,columns:[f('incident','事件'),f('phase','阶段'),f('channel','渠道'),f('recipient_key','接收方'),f('status','状态'),f('attempts','次数'),f('created_at','创建时间',{type:'datetime'})]},
  maintenance:{title:'维护窗口',endpoint:'maintenance-windows',columns:[f('name','名称'),f('start_at','开始时间',{type:'datetime'}),f('end_at','结束时间',{type:'datetime'}),f('is_enabled','启用',{type:'boolean'})],fields:[f('name','名称',{required:true}),f('start_at','开始时间',{type:'datetime',required:true}),f('end_at','结束时间',{type:'datetime',required:true}),f('timezone','时区',{default:'Asia/Shanghai'}),f('reason','原因',{type:'textarea'}),f('recurrence','周期配置',{type:'json',default:{}}),f('continue_probing','继续探测',{type:'boolean',default:true}),f('suppress_notifications','抑制通知',{type:'boolean',default:true}),f('exclude_from_sla','从SLA排除',{type:'boolean',default:true}),f('businesses','业务范围',{type:'relation',endpoint:'business-systems',multiple:true}),f('monitors','探测范围',{type:'relation',endpoint:'monitors',multiple:true}),f('is_enabled','启用',{type:'boolean',default:true})]},
  'status-pages':{title:'状态页',endpoint:'status-pages',columns:[f('name','名称'),f('slug','访问标识'),f('access_mode','访问方式'),f('is_enabled','启用',{type:'boolean'})],actions:['rotate-token'],fields:[f('name','名称',{required:true}),f('slug','访问标识',{required:true}),f('description','描述',{type:'textarea'}),f('access_mode','访问方式',{type:'select',options:['PUBLIC','TOKEN'],default:'TOKEN'}),f('theme_color','主题颜色',{default:'#0c6c79'}),f('businesses','展示业务',{type:'relation',endpoint:'business-systems',multiple:true}),f('monitors','展示探测',{type:'relation',endpoint:'monitors',multiple:true}),f('is_enabled','启用',{type:'boolean',default:true})]},
  users:{title:'用户管理',endpoint:'users',columns:[f('username','用户名'),f('email','邮箱'),f('is_active','启用',{type:'boolean'}),f('is_staff','后台权限',{type:'boolean'}),f('date_joined','创建时间',{type:'datetime'})],fields:[f('username','用户名',{required:true}),f('password','初始密码（至少8位）'),f('first_name','名'),f('last_name','姓'),f('email','邮箱'),f('is_active','启用',{type:'boolean',default:true}),f('is_staff','后台权限',{type:'boolean',default:false})]},
  departments:{title:'部门管理',endpoint:'departments',columns:[f('name','名称'),f('code','编码'),f('parent','上级部门')],fields:[f('name','名称',{required:true}),f('code','编码',{required:true}),f('parent','上级部门',{type:'relation',endpoint:'departments'})]},
  roles:{title:'角色管理',endpoint:'roles',columns:[f('name','名称'),f('code','编码')],fields:[f('name','名称',{required:true}),f('code','编码',{required:true}),f('permissions','权限列表',{type:'json',default:[]}),f('users','用户',{type:'relation',endpoint:'users',multiple:true})]},
  audit:{title:'审计日志',endpoint:'audit-logs',readonly:true,columns:[f('actor','操作者'),f('action','操作'),f('resource_type','资源类型'),f('resource_id','资源ID'),f('source_ip','来源IP'),f('created_at','时间',{type:'datetime'})]},
}
