<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
import TableActionButton from '../components/TableActionButton.vue'
const rows=ref<any[]>([]),monitors=ref<any[]>([]),channels=ref<any[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false),search=ref(''),severity=ref(''),form=ref<any>({})
const levels=['CRITICAL','HIGH','MEDIUM','LOW'],levelName:any={CRITICAL:'严重',HIGH:'高',MEDIUM:'中',LOW:'低'}
async function load(){loading.value=true;try{const{data}=await client.get('/alert-rules/',{params:{search:search.value,severity:severity.value||undefined,page_size:100}});rows.value=data.results||data}finally{loading.value=false}}
async function loadOptions(){const[m,c]=await Promise.all([client.get('/monitors/',{params:{page_size:500}}),client.get('/notification-channels/',{params:{page_size:500}})]);monitors.value=m.data.results||m.data;channels.value=(c.data.results||c.data).filter((item:any)=>item.is_enabled)}
function open(row?:any){form.value=row?{...row,monitors:[...(row.monitors||[])],channels:[...(row.channels||[])]}:{name:'',severity:'HIGH',repeat_interval_minutes:30,escalation_minutes:60,monitors:[],channels:[],is_enabled:true};dialog.value=true}
async function save(){if(!form.value.name?.trim())return ElMessage.warning('请输入规则名称');if(!form.value.monitors?.length)return ElMessage.warning('请至少选择一个探测任务');if(!form.value.channels?.length)return ElMessage.warning('请至少选择一个通知渠道');if(form.value.escalation_minutes<form.value.repeat_interval_minutes)return ElMessage.warning('升级时间不能小于重复间隔');saving.value=true;try{form.value.id?await client.patch(`/alert-rules/${form.value.id}/`,form.value):await client.post('/alert-rules/',form.value);dialog.value=false;ElMessage.success('告警规则保存成功');load()}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data||'保存失败'))}finally{saving.value=false}}
async function toggle(row:any){await client.post(`/alert-rules/${row.id}/toggle/`,{enabled:!row.is_enabled});ElMessage.success(row.is_enabled?'规则已停用':'规则已启用');load()}
async function remove(row:any){await ElMessageBox.confirm(`确认删除规则“${row.name}”？`,'删除确认',{type:'warning'});await client.delete(`/alert-rules/${row.id}/`);ElMessage.success('删除成功');load()}
onMounted(()=>{load();loadOptions()})
</script>
<template><div class="heading"><div><h2>告警规则</h2><p>定义告警级别、重复通知与升级策略</p></div><div class="toolbar"><el-input v-model="search" clearable placeholder="搜索规则" @keyup.enter="load"/><el-select v-model="severity" clearable placeholder="全部级别"><el-option v-for="v in levels" :key="v" :label="levelName[v]" :value="v"/></el-select><el-button @click="load">查询</el-button><el-button type="primary" @click="open()">新增规则</el-button></div></div>
<el-alert title="规则触发后按重复间隔持续通知；达到升级时间后提升通知优先级。停用规则不会参与新事件告警。" type="info" :closable="false" class="guide"/>
<el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="name" label="规则名称" min-width="220"><template #default="s"><b>{{s.row.name}}</b><small>{{s.row.is_enabled?'规则运行中':'规则已停用'}}</small></template></el-table-column><el-table-column label="告警级别" width="120"><template #default="s"><el-tag :type="s.row.severity==='CRITICAL'||s.row.severity==='HIGH'?'danger':s.row.severity==='MEDIUM'?'warning':'info'">{{levelName[s.row.severity]}}</el-tag></template></el-table-column><el-table-column label="探测任务" width="120"><template #default="s">{{s.row.monitors?.length||0}} 项</template></el-table-column><el-table-column label="通知渠道" width="120"><template #default="s">{{s.row.channels?.length||0}} 个</template></el-table-column><el-table-column label="重复通知" width="150"><template #default="s">每 {{s.row.repeat_interval_minutes}} 分钟</template></el-table-column><el-table-column label="升级策略" width="170"><template #default="s">持续 {{s.row.escalation_minutes}} 分钟后升级</template></el-table-column><el-table-column label="状态" width="110"><template #default="s"><el-switch :model-value="s.row.is_enabled" @change="toggle(s.row)"/></template></el-table-column><el-table-column label="操作" width="190"><template #default="s"><div class="actions"><TableActionButton icon="edit" label="编辑" tone="primary" @click="open(s.row)"/><TableActionButton icon="delete" label="删除" tone="danger" @click="remove(s.row)"/></div></template></el-table-column></el-table></el-card>
<el-dialog v-model="dialog" :title="form.id?'编辑告警规则':'新增告警规则'" width="680px"><el-form label-width="150px"><el-form-item label="规则名称" required><el-input v-model="form.name" placeholder="如：核心业务严重故障"/></el-form-item><el-form-item label="探测任务" required><el-select v-model="form.monitors" multiple filterable collapse-tags collapse-tags-tooltip style="width:100%" placeholder="选择触发此规则的探测任务"><el-option v-for="m in monitors" :key="m.id" :label="`${m.business_name} / ${m.name}`" :value="m.id"/></el-select><small>只有所选探测任务发生故障时才触发此规则</small></el-form-item><el-form-item label="通知渠道" required><el-select v-model="form.channels" multiple filterable collapse-tags collapse-tags-tooltip style="width:100%" placeholder="选择告警发送渠道"><el-option v-for="c in channels" :key="c.id" :label="`${c.name}（${c.channel_type}）`" :value="c.id"/></el-select><small>仅显示已启用的通知渠道</small></el-form-item><el-form-item label="默认告警级别" required><el-select v-model="form.severity" style="width:100%"><el-option v-for="v in levels" :key="v" :label="levelName[v]" :value="v"/></el-select></el-form-item><el-form-item label="重复通知间隔" required><el-input-number v-model="form.repeat_interval_minutes" :min="1" :max="1440" style="width:100%"/><small>事件未恢复时，按此间隔再次发送通知</small></el-form-item><el-form-item label="告警升级时间" required><el-input-number v-model="form.escalation_minutes" :min="1" :max="10080" style="width:100%"/><small>必须大于或等于重复通知间隔</small></el-form-item><el-form-item label="启用规则"><el-switch v-model="form.is_enabled"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存规则</el-button></template></el-dialog></template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:16px}.heading h2{margin:0;color:#172b43}.heading p{margin:5px 0 0;color:#8492a5}.toolbar,.actions{display:flex;gap:8px}.toolbar .el-input{width:210px}.toolbar .el-select{width:130px}.guide{margin-bottom:14px}small{display:block;color:#8391a3;font-size:12px;margin-top:5px}.el-form-item small{width:100%}</style>
