<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import client from '../api/client'
const rows=ref<any[]>([]),loading=ref(false),search=ref(''),action=ref(''),result=ref(''),dates=ref<any[]>([]),detail=ref<any>(),drawer=ref(false)
const actions:any={CREATE:'新增',UPDATE:'修改',DELETE:'删除',ARCHIVE:'归档',MAINTENANCE:'系统维护'}
const fmt=(v:string)=>v?new Date(v).toLocaleString():'—'
async function load(){loading.value=true;try{const params:any={search:search.value||undefined,action:action.value||undefined,result:result.value||undefined,ordering:'-created_at',page_size:100};if(dates.value?.length){params.created_after=dates.value[0];params.created_before=dates.value[1]}const{data}=await client.get('/audit-logs/',{params});rows.value=data.results||data}catch(e:any){ElMessage.error(e.response?.data?.message||'审计日志加载失败')}finally{loading.value=false}}
function show(row:any){detail.value=row;drawer.value=true} function reset(){search.value='';action.value='';result.value='';dates.value=[];load()} onMounted(load)
</script>
<template><div class="heading"><div><h2>审计日志</h2><p>追踪用户操作、来源地址、请求标识与执行结果</p></div><div class="toolbar"><el-input v-model="search" clearable placeholder="操作者 / 资源 / IP" @keyup.enter="load"/><el-select v-model="action" clearable placeholder="全部操作"><el-option v-for="(v,k) in actions" :key="k" :label="v" :value="k"/></el-select><el-select v-model="result" clearable placeholder="全部结果"><el-option label="成功" value="SUCCESS"/><el-option label="失败" value="FAILED"/></el-select><el-date-picker v-model="dates" type="datetimerange" value-format="YYYY-MM-DDTHH:mm:ssZ" start-placeholder="开始时间" end-placeholder="结束时间"/><el-button @click="reset">重置</el-button><el-button type="primary" @click="load">查询</el-button></div></div>
<el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe @row-click="show"><el-table-column label="操作者" min-width="140"><template #default="s"><b>{{s.row.actor_name}}</b><small>{{s.row.source_ip||'本机/未知'}}</small></template></el-table-column><el-table-column label="操作" width="110"><template #default="s"><el-tag effect="plain">{{actions[s.row.action]||s.row.action}}</el-tag></template></el-table-column><el-table-column prop="resource_type" label="资源类型" min-width="140"/><el-table-column prop="resource_id" label="资源标识" min-width="190" show-overflow-tooltip/><el-table-column label="结果" width="90"><template #default="s"><el-tag :type="s.row.result==='SUCCESS'?'success':'danger'">{{s.row.result==='SUCCESS'?'成功':'失败'}}</el-tag></template></el-table-column><el-table-column label="操作时间" width="180"><template #default="s">{{fmt(s.row.created_at)}}</template></el-table-column><el-table-column label="详情" width="80"><template #default="s"><el-button link type="primary" @click.stop="show(s.row)">查看</el-button></template></el-table-column></el-table></el-card>
<el-drawer v-model="drawer" title="审计详情" size="520px"><template v-if="detail"><el-descriptions :column="1" border><el-descriptions-item label="操作者">{{detail.actor_name}}</el-descriptions-item><el-descriptions-item label="操作">{{actions[detail.action]||detail.action}}</el-descriptions-item><el-descriptions-item label="资源">{{detail.resource_type}} / {{detail.resource_id}}</el-descriptions-item><el-descriptions-item label="结果">{{detail.result}}</el-descriptions-item><el-descriptions-item label="来源 IP">{{detail.source_ip||'—'}}</el-descriptions-item><el-descriptions-item label="请求 ID">{{detail.request_id||'—'}}</el-descriptions-item><el-descriptions-item label="时间">{{fmt(detail.created_at)}}</el-descriptions-item></el-descriptions><h4>操作明细</h4><pre>{{JSON.stringify(detail.detail||{},null,2)}}</pre></template></el-drawer></template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:16px}.heading h2{margin:0;color:#192c42}.heading p{margin:5px 0 0;color:#7f8e9f}.toolbar{display:flex;gap:7px}.toolbar .el-input{width:190px}.toolbar .el-select{width:115px}.toolbar .el-date-editor{width:330px}small{display:block;color:#8794a3;margin-top:4px}pre{padding:14px;color:#d8e7f1;background:#162a3d;border-radius:6px;white-space:pre-wrap;word-break:break-all;max-height:360px;overflow:auto}</style>
