<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
import TableActionButton from '../components/TableActionButton.vue'

const rows=ref<any[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false),form=ref<any>({})
async function load(){loading.value=true;try{const {data}=await client.get('/departments/',{params:{page_size:500,_t:Date.now()}});rows.value=data.results||data}catch(e:any){ElMessage.error(e.response?.data?.message||e.response?.data?.detail||'部门加载失败')}finally{loading.value=false}}
function add(){form.value={name:'',code:'',parent:null,description:'',sort_order:0,is_enabled:true};dialog.value=true}
function edit(row:any){form.value={...row};dialog.value=true}
async function save(){if(!form.value.name||!form.value.code)return ElMessage.warning('请填写部门名称和编码');saving.value=true;try{const payload={...form.value};payload.id?await client.patch(`/departments/${payload.id}/`,payload):await client.post('/departments/',payload);dialog.value=false;ElMessage.success('部门保存成功');await load()}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data?.details||e.response?.data||'保存失败'))}finally{saving.value=false}}
async function remove(row:any){await ElMessageBox.confirm(`确定删除部门“${row.name}”吗？`,'删除部门',{type:'warning'});try{await client.delete(`/departments/${row.id}/`);ElMessage.success('部门已删除');load()}catch(e:any){ElMessage.error(e.response?.data?.details?.detail||e.response?.data?.detail||'删除失败')}}
onMounted(load)
</script>
<template><section><div class="page-head"><div><h2 class="page-title">部门管理</h2><div class="page-subtitle">维护组织层级、部门状态及成员归属</div></div><el-button type="primary" @click="add">＋ 新增部门</el-button></div><el-card><el-table v-loading="loading" :data="rows" row-key="id" stripe><el-table-column prop="name" label="部门名称" min-width="180"/><el-table-column prop="code" label="部门编码" width="150"/><el-table-column label="上级部门" min-width="160"><template #default="s">{{s.row.parent_name||'—'}}</template></el-table-column><el-table-column prop="user_count" label="成员数" width="100"/><el-table-column prop="sort_order" label="排序" width="90"/><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.is_enabled?'success':'info'">{{s.row.is_enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="s"><div class="actions"><TableActionButton icon="edit" label="编辑" tone="primary" @click="edit(s.row)"/><TableActionButton icon="delete" label="删除" tone="danger" icon-only @click="remove(s.row)"/></div></template></el-table-column></el-table></el-card><el-dialog v-model="dialog" :title="form.id?'编辑部门':'新增部门'" width="600px"><el-form label-position="top"><div class="grid"><el-form-item label="部门名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="部门编码" required><el-input v-model="form.code" placeholder="如 TECH"/></el-form-item><el-form-item label="上级部门"><el-select v-model="form.parent" clearable style="width:100%"><el-option v-for="item in rows.filter(x=>x.id!==form.id)" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="显示顺序"><el-input-number v-model="form.sort_order" :min="0" style="width:100%"/></el-form-item></div><el-form-item label="部门说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="启用部门"><el-switch v-model="form.is_enabled"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.actions{display:flex;gap:6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}</style>
