<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
import TableActionButton from '../components/TableActionButton.vue'
const page=ref(1),pageSize=ref(20),total=ref(0)
function searchRows(){page.value=1;load()}
const rows=ref<any[]>([]),loading=ref(false),search=ref(''),status=ref(''),severity=ref(''),detail=ref<any>(),drawer=ref(false)
const statuses:any={NEW:'新建',ACKNOWLEDGED:'已确认',PROCESSING:'处理中',RECOVERED:'已恢复',CLOSED:'已关闭'}
const levels:any={CRITICAL:'严重',HIGH:'高',MEDIUM:'中',LOW:'低'}
const tagType=(v:string)=>({CRITICAL:'danger',HIGH:'danger',MEDIUM:'warning',LOW:'info',NEW:'danger',ACKNOWLEDGED:'warning',PROCESSING:'primary',RECOVERED:'success',CLOSED:'info'} as any)[v]
const fmt=(v:string)=>v?new Date(v).toLocaleString():'—'
async function load(){loading.value=true;try{const{data}=await client.get('/incidents/',{params:{search:search.value,status:status.value||undefined,severity:severity.value||undefined,page:page.value,page_size:pageSize.value,ordering:'-opened_at'}});rows.value=data.results||data;total.value=data.count??rows.value.length}catch{ElMessage.error('故障事件加载失败')}finally{loading.value=false}}
async function show(row:any){const{data}=await client.get(`/incidents/${row.id}/`);detail.value=data;drawer.value=true}
async function action(row:any,name:string){try{if(name==='close'){const{value}=await ElMessageBox.prompt('请填写解决说明','关闭故障事件',{inputType:'textarea',inputValidator:v=>!!String(v).trim()||'解决说明不能为空'});await client.post(`/incidents/${row.id}/close/`,{resolution:value})}else await client.post(`/incidents/${row.id}/${name}/`,name==='process'?{comment:'开始处理'}:{});ElMessage.success(name==='acknowledge'?'事件已确认':name==='process'?'事件已转为处理中':'事件已关闭');await load();if(drawer.value)await show(row)}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.resolution||e.response?.data?.status||'操作失败')}}
async function remove(row:any){try{await ElMessageBox.confirm(`确认删除故障事件 ${row.number}？事件时间线和关联发送记录将同时删除，此操作不可撤销。`,'删除故障事件',{type:'warning',confirmButtonText:'确认删除',cancelButtonText:'取消'});await client.delete(`/incidents/${row.id}/`);if(detail.value?.id===row.id){drawer.value=false;detail.value=undefined}ElMessage.success('故障事件已删除');await load()}catch(e:any){if(e==='cancel'||e==='close')return;ElMessage.error(e.response?.data?.detail||'删除失败，请检查权限或关联数据')}}
onMounted(load)
</script>
<template><div class="heading"><div><h2>故障事件</h2><p>跟踪故障发现、确认、处理、恢复与关闭全过程</p></div><div class="filters"><el-input v-model="search" clearable placeholder="事件编号 / 标题" @keyup.enter="searchRows"/><el-select v-model="severity" clearable placeholder="故障级别"><el-option v-for="(v,k) in levels" :key="k" :label="v" :value="k"/></el-select><el-select v-model="status" clearable placeholder="事件状态"><el-option v-for="(v,k) in statuses" :key="k" :label="v" :value="k"/></el-select><el-button type="primary" @click="searchRows">查询</el-button></div></div>
<div class="summary"><div><b>{{rows.length}}</b><span>事件总数</span></div><div><b>{{rows.filter(x=>!['CLOSED','RECOVERED'].includes(x.status)).length}}</b><span>待处理</span></div><div><b>{{rows.filter(x=>x.severity==='CRITICAL').length}}</b><span>严重事件</span></div><div><b>{{rows.filter(x=>x.status==='RECOVERED').length}}</b><span>等待关闭</span></div></div>
<el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column label="事件" min-width="250"><template #default="s"><a class="event-link" @click="show(s.row)">{{s.row.number}}</a><small>{{s.row.title}}</small></template></el-table-column><el-table-column label="业务 / 探测" min-width="190"><template #default="s">{{s.row.business_name}}<small>{{s.row.monitor_name}}</small></template></el-table-column><el-table-column label="级别" width="90"><template #default="s"><el-tag :type="tagType(s.row.severity)">{{levels[s.row.severity]}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="tagType(s.row.status)" effect="plain">{{statuses[s.row.status]}}</el-tag></template></el-table-column><el-table-column label="负责人" width="120"><template #default="s">{{s.row.assignee_name||'未分配'}}</template></el-table-column><el-table-column label="发现时间" width="180"><template #default="s">{{fmt(s.row.opened_at)}}</template></el-table-column><el-table-column label="操作" width="330" fixed="right"><template #default="s"><div class="actions"><TableActionButton icon="check" label="确认" tone="primary" :disabled="s.row.status!=='NEW'" @click="action(s.row,'acknowledge')"/><TableActionButton icon="run" label="处理" tone="primary" :disabled="!['NEW','ACKNOWLEDGED'].includes(s.row.status)" @click="action(s.row,'process')"/><TableActionButton icon="close" label="关闭" tone="danger" :disabled="s.row.status==='CLOSED'" @click="action(s.row,'close')"/><TableActionButton icon="delete" label="删除" tone="danger" icon-only @click="remove(s.row)"/></div></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" background @current-change="load" @size-change="searchRows"/></el-card>
<el-drawer v-model="drawer" title="事件详情" size="540px"><template v-if="detail"><div class="detail-head"><el-tag :type="tagType(detail.severity)">{{levels[detail.severity]}}</el-tag><h3>{{detail.title}}</h3><span>{{detail.number}} · {{statuses[detail.status]}}</span><el-button type="danger" plain size="small" @click="remove(detail)">删除事件</el-button></div><el-descriptions :column="1" border><el-descriptions-item label="业务系统">{{detail.business_name}}</el-descriptions-item><el-descriptions-item label="探测任务">{{detail.monitor_name}}</el-descriptions-item><el-descriptions-item label="事件摘要">{{detail.summary||'暂无'}}</el-descriptions-item><el-descriptions-item label="负责人">{{detail.assignee_name||'未分配'}}</el-descriptions-item><el-descriptions-item label="根因">{{detail.root_cause||'待分析'}}</el-descriptions-item><el-descriptions-item label="解决说明">{{detail.resolution||'待填写'}}</el-descriptions-item></el-descriptions><h4>处理时间线</h4><el-timeline><el-timeline-item v-for="t in detail.timeline" :key="t.id" :timestamp="fmt(t.occurred_at)"><b>{{statuses[t.action]||t.action}}</b><p v-if="t.payload?.comment">{{t.payload.comment}}</p><p v-if="t.payload?.resolution">{{t.payload.resolution}}</p></el-timeline-item></el-timeline></template></el-drawer></template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:16px}.heading h2{margin:0;color:#172b43}.heading p{margin:5px 0 0;color:#8492a5}.filters,.actions{display:flex;gap:8px}.filters .el-input{width:210px}.filters .el-select{width:130px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.summary>div{background:#fff;border:1px solid #dfe6ed;border-left:4px solid #2876aa;padding:15px 18px;border-radius:6px}.summary b,.summary span,small{display:block}.summary b{font-size:24px;color:#173652}.summary span,small{font-size:12px;color:#8190a2;margin-top:4px}.event-link{color:#176da5;font-weight:700;cursor:pointer}.detail-head{position:relative;padding-bottom:18px}.detail-head h3{margin:12px 0 6px}.detail-head span{color:#77879a}.detail-head .el-button{position:absolute;right:0;top:0}.el-drawer h4{margin-top:24px}.el-timeline p{margin:5px 0;color:#697a8e}</style>
