<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
const rows=ref<any[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false),state=ref(''),form=ref<any>({}),businesses=ref<any[]>([]),monitors=ref<any[]>([])
const statusText:any={ACTIVE:'进行中',UPCOMING:'即将开始',ENDED:'已结束',DISABLED:'已停用'}
const fmt=(v:string)=>v?new Date(v).toLocaleString():'—'
async function load(){loading.value=true;try{const{data}=await client.get('/maintenance-windows/',{params:{state:state.value||undefined,page_size:100}});rows.value=data.results||data}finally{loading.value=false}}
async function options(){const[b,m]=await Promise.all([client.get('/business-systems/',{params:{page_size:200,is_archived:false}}),client.get('/monitors/',{params:{page_size:200}})]);businesses.value=b.data.results||b.data;monitors.value=m.data.results||m.data}
function fresh(){return{name:'',start_at:'',end_at:'',timezone:'Asia/Shanghai',reason:'',recurrence:{},continue_probing:true,suppress_notifications:true,exclude_from_sla:true,businesses:[],monitors:[],is_enabled:true}}
async function open(row?:any){form.value=row?{...row}:fresh();dialog.value=true;await options()}
async function save(){saving.value=true;try{const payload={...form.value,recurrence:{}};payload.id?await client.patch(`/maintenance-windows/${payload.id}/`,payload):await client.post('/maintenance-windows/',payload);ElMessage.success('维护窗口已保存');dialog.value=false;load()}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data?.details||e.response?.data||'保存失败'))}finally{saving.value=false}}
async function remove(row:any){await ElMessageBox.confirm(`确认删除“${row.name}”？`,'删除维护窗口',{type:'warning'});await client.delete(`/maintenance-windows/${row.id}/`);ElMessage.success('已删除');load()}
onMounted(load)
</script>
<template><div class="heading"><div><h2>维护窗口</h2><p>控制告警抑制、探测执行与 SLA 统计排除范围</p></div><div class="toolbar"><el-select v-model="state" clearable placeholder="全部状态" @change="load"><el-option v-for="(v,k) in statusText" :key="k" :label="v" :value="k"/></el-select><el-button @click="load">刷新</el-button><el-button type="primary" @click="open()">新增维护窗口</el-button></div></div>
<div class="summary"><div><b>{{rows.filter(x=>x.status==='ACTIVE').length}}</b><span>正在维护</span></div><div><b>{{rows.filter(x=>x.status==='UPCOMING').length}}</b><span>即将开始</span></div><div><b>{{rows.filter(x=>x.exclude_from_sla).length}}</b><span>排除 SLA</span></div><div><b>{{rows.filter(x=>x.suppress_notifications).length}}</b><span>抑制通知</span></div></div>
<el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column label="维护窗口" min-width="190"><template #default="s"><b>{{s.row.name}}</b><small>{{s.row.reason||'未填写维护原因'}}</small></template></el-table-column><el-table-column label="状态" width="110"><template #default="s"><el-tag :type="s.row.status==='ACTIVE'?'warning':s.row.status==='UPCOMING'?'primary':s.row.status==='DISABLED'?'info':''">{{statusText[s.row.status]}}</el-tag></template></el-table-column><el-table-column label="时间范围" min-width="250"><template #default="s">{{fmt(s.row.start_at)}}<small>至 {{fmt(s.row.end_at)}}（{{s.row.timezone}}）</small></template></el-table-column><el-table-column label="作用范围" min-width="210"><template #default="s"><span>{{s.row.business_names?.join('、')||'指定探测任务'}}</span><small>{{s.row.monitor_names?.join('、')||'业务下全部探测'}}</small></template></el-table-column><el-table-column label="策略" min-width="180"><template #default="s"><el-tag v-if="s.row.suppress_notifications" size="small">抑制通知</el-tag> <el-tag v-if="s.row.exclude_from_sla" size="small" type="success">排除 SLA</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table></el-card>
<el-dialog v-model="dialog" :title="form.id?'编辑维护窗口':'新增维护窗口'" width="720px"><el-form label-width="130px"><el-form-item label="名称" required><el-input v-model="form.name" placeholder="例如：核心数据库升级维护"/></el-form-item><el-form-item label="开始时间" required><el-date-picker v-model="form.start_at" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width:100%"/></el-form-item><el-form-item label="结束时间" required><el-date-picker v-model="form.end_at" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width:100%"/></el-form-item><el-form-item label="时区"><el-input v-model="form.timezone"/></el-form-item><el-form-item label="维护原因"><el-input v-model="form.reason" type="textarea" :rows="3"/></el-form-item><el-form-item label="业务系统"><el-select v-model="form.businesses" multiple filterable clearable style="width:100%"><el-option v-for="x in businesses" :key="x.id" :label="x.name" :value="x.id"/></el-select><small>选择业务后自动覆盖该业务下全部有效探测任务</small></el-form-item><el-form-item label="探测任务"><el-select v-model="form.monitors" multiple filterable clearable style="width:100%"><el-option v-for="x in monitors" :key="x.id" :label="`${x.name} · ${x.target}`" :value="x.id"/></el-select></el-form-item><el-form-item label="维护策略"><el-checkbox v-model="form.continue_probing">继续探测</el-checkbox><el-checkbox v-model="form.suppress_notifications">抑制通知</el-checkbox><el-checkbox v-model="form.exclude_from_sla">从 SLA 排除</el-checkbox></el-form-item><el-form-item label="启用"><el-switch v-model="form.is_enabled"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:15px}.heading h2{margin:0}.heading p{margin:5px 0 0;color:#7d8b9c}.toolbar{display:flex;gap:8px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.summary>div{padding:14px 18px;background:#fff;border:1px solid #dfe6ed;border-left:4px solid #3d80aa;border-radius:6px}.summary b,.summary span,small{display:block}.summary b{font-size:23px}.summary span,small{font-size:12px;color:#8290a0;margin-top:4px}</style>
