<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
import TableActionButton from '../components/TableActionButton.vue'
const rows=ref<any[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false),testing=ref(''),search=ref(''),form=ref<any>({})
const types:any={EMAIL:{label:'邮件 SMTP',desc:'通过企业邮箱或SMTP服务器发送告警邮件'},WECHAT:{label:'企业微信机器人',desc:'通过群机器人 Webhook 推送文本告警'},DINGTALK:{label:'钉钉机器人',desc:'支持自定义机器人 Webhook 和加签密钥'},WEBHOOK:{label:'通用 Webhook',desc:'向指定HTTP接口发送标准JSON事件'},SERVERCHAN:{label:'Server酱',desc:'通过 Server酱 SendKey 推送至微信及已配置渠道'}}
const fields=computed<any[]>(()=>(({
 EMAIL:[['host','SMTP服务器','如 smtp.example.com','text',true],['port','SMTP端口','SSL常用465，STARTTLS常用587','number',false],['username','登录用户名','通常为完整邮箱地址','text',false],['password','登录密码/授权码','编辑时保留 ******** 即不修改','password',false],['from_email','发件人地址','告警邮件显示的发件地址','text',true],['recipients','收件人列表','多个地址用英文逗号分隔','textarea',true],['timeout','连接超时（秒）','1-60秒','number',false]],
 WECHAT:[['webhook_url','机器人 Webhook URL','企业微信群机器人完整地址','text',true],['timeout','请求超时（秒）','1-60秒','number',false],['headers','附加请求头','JSON对象，可选','json',false]],
 DINGTALK:[['webhook_url','机器人 Webhook URL','钉钉自定义机器人完整地址','text',true],['secret','加签密钥','SEC开头；编辑时 ******** 表示不修改','password',false],['timeout','请求超时（秒）','1-60秒','number',false],['headers','附加请求头','JSON对象，可选','json',false]],
 WEBHOOK:[['url','接收地址 URL','必须为 http 或 https 地址','text',true],['timeout','请求超时（秒）','1-60秒','number',false],['headers','请求头','JSON对象，如 Authorization','json',false]],
 SERVERCHAN:[['sendkey','SendKey','从 Server酱后台获取；编辑时 ******** 表示不修改','password',true],['tags','消息标签','多个标签使用竖线 | 分隔','text',false],['short','消息摘要','微信卡片摘要，可选','textarea',false],['channel','推送通道','多个通道用竖线 | 分隔，如 9|66','text',false],['openid','指定 OpenID','多个 OpenID 用逗号或竖线分隔','text',false],['timeout','请求超时（秒）','1-60秒','number',false]],
} as Record<string,any[]>)[form.value.channel_type]||[]))
async function load(){loading.value=true;try{const{data}=await client.get('/notification-channels/',{params:{search:search.value,page_size:100}});rows.value=data.results||data}catch{ElMessage.error('通知渠道加载失败')}finally{loading.value=false}}
function defaults(type='EMAIL'){if(type==='EMAIL')return {port:465,use_ssl:true,use_tls:false,timeout:10,recipients:''};if(type==='SERVERCHAN')return {timeout:10,noip:false};return {timeout:10,headers:{}}}
function create(){form.value={name:'',channel_type:'EMAIL',is_enabled:true,config:defaults('EMAIL')};dialog.value=true}
function edit(row:any){form.value={...row,config:{...defaults(row.channel_type),...(row.config||{})}};dialog.value=true}
function changeType(type:string){form.value.config=defaults(type)}
async function save(){saving.value=true;try{const payload=JSON.parse(JSON.stringify(form.value));for(const f of fields.value)if(f[3]==='json'&&typeof payload.config[f[0]]==='string')payload.config[f[0]]=JSON.parse(payload.config[f[0]]||'{}');payload.id?await client.patch(`/notification-channels/${payload.id}/`,payload):await client.post('/notification-channels/',payload);dialog.value=false;ElMessage.success('通知渠道保存成功');load()}catch(e:any){const data=e.response?.data;const detail=data?.config||data?.details?.config||data?.name||data?.non_field_errors;ElMessage.error(Array.isArray(detail)?detail.join('；'):detail||e.message||'保存失败')}finally{saving.value=false}}
async function test(row:any){testing.value=row.id;try{const{data}=await client.post(`/notification-channels/${row.id}/test/`);ElMessage.success(`${data.message}，耗时 ${data.latency_ms} ms`)}catch(e:any){ElMessage.error(e.response?.data?.message||'渠道测试失败')}finally{testing.value=''}}
async function remove(row:any){await ElMessageBox.confirm(`确认删除通知渠道“${row.name}”？`,'删除确认',{type:'warning'});await client.delete(`/notification-channels/${row.id}/`);ElMessage.success('删除成功');load()}
onMounted(load)
</script>
<template><div class="heading"><div><h2>通知渠道</h2><p>配置并验证告警消息的实际发送链路</p></div><div class="toolbar"><el-input v-model="search" clearable placeholder="搜索渠道名称" @keyup.enter="load"/><el-button @click="load">查询</el-button><el-button type="primary" @click="create">新增渠道</el-button></div></div>
<div class="type-guide"><div v-for="(t,key) in types" :key="key"><b>{{t.label}}</b><span>{{t.desc}}</span></div></div>
<el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe empty-text="暂无通知渠道"><el-table-column label="渠道名称" min-width="180"><template #default="s"><b>{{s.row.name}}</b></template></el-table-column><el-table-column label="渠道类型" width="170"><template #default="s"><el-tag effect="plain">{{types[s.row.channel_type]?.label}}</el-tag></template></el-table-column><el-table-column label="关键配置" min-width="260"><template #default="s"><span class="summary">{{s.row.channel_type==='EMAIL'?`${s.row.config.host||'未配置'}:${s.row.config.port||'—'} · ${s.row.config.recipients||'无收件人'}`:s.row.channel_type==='SERVERCHAN'?`SendKey ${s.row.config.sendkey||'未配置'}`:(s.row.config.webhook_url||s.row.config.url||'未配置地址')}}</span></template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.is_enabled?'success':'info'">{{s.row.is_enabled?'已启用':'已停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="244" fixed="right" align="center"><template #default="s"><div class="actions"><TableActionButton icon="run" label="测试渠道" tone="primary" :disabled="testing===s.row.id" @click="test(s.row)"/><TableActionButton icon="edit" label="编辑" tone="primary" @click="edit(s.row)"/><TableActionButton icon="delete" label="删除" tone="danger" icon-only @click="remove(s.row)"/></div></template></el-table-column></el-table></el-card>
<el-dialog v-model="dialog" :title="form.id?'编辑通知渠道':'新增通知渠道'" width="720px"><el-alert :title="types[form.channel_type]?.desc" type="info" :closable="false" class="hint"/><el-form label-width="150px"><el-form-item label="渠道名称" required><el-input v-model="form.name" placeholder="便于识别的渠道名称"/></el-form-item><el-form-item label="渠道类型" required><el-select v-model="form.channel_type" style="width:100%" :disabled="!!form.id" @change="changeType"><el-option v-for="(t,key) in types" :key="key" :label="t.label" :value="key"/></el-select></el-form-item><el-divider content-position="left">{{types[form.channel_type]?.label}} 参数</el-divider><el-form-item v-for="f in fields" :key="f[0] as string" :label="f[1] as string" :required="f[4] as boolean"><el-input-number v-if="f[3]==='number'" v-model="form.config[f[0]]" :min="1" :max="f[0]==='timeout'?60:65535" style="width:100%"/><el-input v-else v-model="form.config[f[0]]" :type="f[3]==='password'?'password':f[3]==='textarea'||f[3]==='json'?'textarea':'text'" :rows="f[3]==='json'?4:2" show-password :placeholder="f[2] as string"/><small>{{f[2]}}</small></el-form-item><template v-if="form.channel_type==='EMAIL'"><el-form-item label="传输安全"><el-checkbox v-model="form.config.use_ssl" @change="form.config.use_ssl&&(form.config.use_tls=false)">SMTP over SSL</el-checkbox><el-checkbox v-model="form.config.use_tls" @change="form.config.use_tls&&(form.config.use_ssl=false)">STARTTLS</el-checkbox></el-form-item></template><template v-if="form.channel_type==='SERVERCHAN'"><el-form-item label="隐藏调用 IP"><div><el-switch v-model="form.config.noip"/><small>开启后不在推送内容中附加调用方 IP 信息</small></div></el-form-item></template><el-form-item label="启用渠道"><el-switch v-model="form.is_enabled"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存配置</el-button></template></el-dialog></template>
<style scoped>.heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}.heading h2{margin:0;color:#182a40}.heading p{margin:5px 0 0;color:#8290a2;font-size:13px}.toolbar,.actions{display:flex;gap:7px;align-items:center}.toolbar .el-input{width:220px}.type-guide{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-bottom:14px}.type-guide>div{padding:13px 15px;background:#fff;border:1px solid #dfe6ed;border-top:3px solid #2a79ad;border-radius:6px}.type-guide b,.type-guide span{display:block}.type-guide b{font-size:13px;color:#273c53}.type-guide span{font-size:11px;color:#8290a0;margin-top:5px;line-height:1.5}.summary{display:block;max-width:420px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#607185}.hint{margin-bottom:18px}.el-form-item small{display:block;width:100%;color:#8a96a5;font-size:11px;margin-top:4px}@media(max-width:1100px){.type-guide{grid-template-columns:repeat(2,1fr)}}</style>
