<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
import TableActionButton from '../components/TableActionButton.vue'
const page=ref(1),pageSize=ref(20),total=ref(0)
function searchRows(){page.value=1;load()}
const rows=ref<any[]>([]),loading=ref(false),search=ref(''),status=ref(''),detail=ref<any>(),drawer=ref(false),retrying=ref('')
const statuses:any={PENDING:'等待发送',SENT:'发送成功',FAILED:'发送失败',RETRYING:'重试中'}
const phases:any={OPEN:'故障通知',REPEAT:'故障持续提醒',RECOVERY:'恢复通知'}
const fmt=(v:string)=>v?new Date(v).toLocaleString():'—'
async function load(){loading.value=true;try{const{data}=await client.get('/notification-logs/',{params:{search:search.value,status:status.value||undefined,page:page.value,page_size:pageSize.value,ordering:'-created_at'}});rows.value=data.results||data;total.value=data.count??rows.value.length}catch{ElMessage.error('发送记录加载失败，请重试')}finally{loading.value=false}}
function show(row:any){detail.value=row;drawer.value=true}
async function retry(row:any){await ElMessageBox.confirm(`确认通过“${row.channel_name}”重新发送该事件通知？`,'重新发送',{type:'warning'});retrying.value=row.id;try{await client.post(`/notification-logs/${row.id}/retry/`);ElMessage.success('通知重新发送成功');load()}catch(e:any){ElMessage.error(e.response?.data?.delivery?.message||e.response?.data?.channel||'重新发送失败')}finally{retrying.value=''}}
onMounted(load)
</script>
<template><div class="heading"><div><h2>发送记录</h2><p>审计告警通知的发送状态、尝试次数与失败原因</p></div><div class="toolbar"><el-input v-model="search" clearable placeholder="事件 / 渠道 / 接收方" @keyup.enter="searchRows"/><el-select v-model="status" clearable placeholder="全部状态"><el-option v-for="(v,k) in statuses" :key="k" :label="v" :value="k"/></el-select><el-button type="primary" @click="searchRows">查询</el-button></div></div>
<div class="summary"><div><b>{{total}}</b><span>筛选记录总数</span></div><div class="ok"><b>{{rows.filter(x=>x.status==='SENT').length}}</b><span>本页发送成功</span></div><div class="bad"><b>{{rows.filter(x=>x.status==='FAILED').length}}</b><span>本页发送失败</span></div><div><b>{{rows.reduce((n,x)=>n+x.attempts,0)}}</b><span>本页累计尝试</span></div></div>
<el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column label="事件" min-width="230"><template #default="s"><a @click="show(s.row)">{{s.row.incident_number}}</a><small>{{s.row.incident_title}}</small></template></el-table-column><el-table-column label="通知渠道" min-width="170"><template #default="s">{{s.row.channel_name}}<small>{{s.row.channel_type}}</small></template></el-table-column><el-table-column label="阶段" width="140"><template #default="s">{{phases[s.row.phase]||s.row.phase}}</template></el-table-column><el-table-column prop="recipient_key" label="接收方" min-width="150" show-overflow-tooltip/><el-table-column label="状态" width="110"><template #default="s"><el-tag :type="s.row.status==='SENT'?'success':s.row.status==='FAILED'?'danger':'warning'">{{statuses[s.row.status]||s.row.status}}</el-tag></template></el-table-column><el-table-column prop="attempts" label="尝试" width="75"/><el-table-column label="发送时间" width="180"><template #default="s">{{fmt(s.row.sent_at||s.row.created_at)}}</template></el-table-column><el-table-column label="操作" width="175"><template #default="s"><div class="actions"><TableActionButton icon="run" label="详情" tone="primary" @click="show(s.row)"/><TableActionButton icon="refresh" label="重试" tone="danger" :disabled="retrying===s.row.id" @click="retry(s.row)"/></div></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" background @current-change="load" @size-change="searchRows"/></el-card>
<el-drawer v-model="drawer" title="发送详情" size="500px"><template v-if="detail"><div class="result" :class="detail.status==='SENT'?'success':'failed'"><b>{{statuses[detail.status]||detail.status}}</b><span>{{detail.incident_number}}</span></div><el-descriptions :column="1" border><el-descriptions-item label="事件标题">{{detail.incident_title}}</el-descriptions-item><el-descriptions-item label="通知渠道">{{detail.channel_name}}（{{detail.channel_type}}）</el-descriptions-item><el-descriptions-item label="通知阶段">{{phases[detail.phase]||detail.phase}}</el-descriptions-item><el-descriptions-item label="接收方">{{detail.recipient_key}}</el-descriptions-item><el-descriptions-item label="尝试次数">{{detail.attempts}}</el-descriptions-item><el-descriptions-item label="创建时间">{{fmt(detail.created_at)}}</el-descriptions-item><el-descriptions-item label="成功时间">{{fmt(detail.sent_at)}}</el-descriptions-item><el-descriptions-item label="失败原因"><span class="error">{{detail.error_summary||'无'}}</span></el-descriptions-item></el-descriptions></template></el-drawer></template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:16px}.heading h2{margin:0;color:#172b43}.heading p{margin:5px 0 0;color:#8492a5}.toolbar,.actions{display:flex;gap:8px}.toolbar .el-input{width:240px}.toolbar .el-select{width:130px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.summary>div{padding:14px 18px;background:#fff;border:1px solid #dfe6ed;border-radius:6px;border-left:4px solid #317da9}.summary .ok{border-left-color:#3b9b70}.summary .bad{border-left-color:#d65d5d}.summary b,.summary span,small{display:block}.summary b{font-size:23px}.summary span,small{font-size:12px;color:#8190a2;margin-top:4px}a{color:#176da5;font-weight:700;cursor:pointer}.result{display:flex;justify-content:space-between;padding:16px;margin-bottom:18px;border-radius:6px}.result.success{background:#edf8f2;color:#26734e}.result.failed{background:#fff1f1;color:#aa4141}.error{color:#b94b4b;word-break:break-all}</style>
