<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import client from '../api/client'
const route=useRoute(),data=ref<any>({monitors:[],summary:{}}),error=ref(''),loading=ref(true)
const labels:any={UP:'运行正常',DOWN:'服务故障',DEGRADED:'性能降级',PAUSED:'已暂停',MAINTENANCE:'维护中',PENDING:'等待探测',UNKNOWN:'状态未知'}
const type=(s:string)=>s==='UP'?'success':s==='DOWN'?'danger':s==='DEGRADED'?'warning':'info'
async function load(){loading.value=true;try{data.value=(await client.get(`/public/status/${route.params.slug}/`,{params:{token:route.query.token}})).data;document.documentElement.style.setProperty('--status-theme',data.value.theme_color)}catch(e:any){error.value=e.response?.data?.detail||'状态页不存在或无权访问'}finally{loading.value=false}}
onMounted(load)
</script>
<template><main class="status"><header><div class="brand">H</div><div><h1>{{data.name||'业务服务状态'}}</h1><p>{{data.description||'实时服务可用性状态'}}</p></div><button @click="load">刷新状态</button></header><el-skeleton v-if="loading" :rows="6" animated/><el-result v-else-if="error" icon="warning" title="无法访问状态页" :sub-title="error"/><template v-else><section class="overall" :class="data.overall_status?.toLowerCase()"><div><i></i><div><b>{{data.overall_status==='UP'?'所有服务运行正常':data.overall_status==='DOWN'?'部分服务发生故障':'部分服务性能降级'}}</b><span>共 {{data.summary.total||0}} 项服务，受影响 {{data.summary.affected||0}} 项</span></div></div><small>更新于 {{new Date(data.updated_at).toLocaleString()}}</small></section><section class="list"><article v-for="m in data.monitors" :key="m.id"><div><b>{{m.name}}</b><span>{{m.business}} · {{m.type}}</span></div><div class="metric"><span>{{m.latency_ms==null?'—':Number(m.latency_ms).toFixed(1)+' ms'}}</span><small>{{m.last_checked_at?new Date(m.last_checked_at).toLocaleString():'尚未探测'}}</small></div><el-tag :type="type(m.status)">{{labels[m.status]||m.status}}</el-tag></article></section><footer>合力数据业务监控系统 · 状态数据自动更新</footer></template></main></template>
<style scoped>.status{--status-theme:#0c6c79;max-width:960px;margin:38px auto;padding:20px;color:#213348}header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:14px;margin-bottom:28px}.brand{width:44px;height:44px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(145deg,var(--status-theme),#133b61);color:#fff;font-size:25px;font-weight:800}h1{font-size:22px;margin:0}header p{color:#7c8b9c;margin:4px 0 0}button{color:var(--status-theme);background:#fff;border:1px solid #d4dde6;border-radius:6px;padding:8px 14px;cursor:pointer}.overall{display:flex;justify-content:space-between;align-items:center;padding:20px 22px;border:1px solid #cde7da;background:#eff9f4;border-radius:8px;color:#226b4b}.overall>div{display:flex;align-items:center;gap:13px}.overall i{display:block;width:13px;height:13px;border-radius:50%;background:#32a66b;box-shadow:0 0 0 7px #32a66b20}.overall b,.overall span{display:block}.overall span,.overall small{font-size:12px;margin-top:5px}.overall.down{color:#9e3f3f;background:#fff1f1;border-color:#efcece}.overall.down i{background:#d55252}.overall.degraded{color:#8c651d;background:#fff8e9;border-color:#eedda8}.list{margin-top:15px;border:1px solid #dde5ec;border-radius:8px;overflow:hidden;background:#fff}.list article{display:grid;grid-template-columns:1fr 190px 110px;align-items:center;padding:16px 19px;border-bottom:1px solid #e9edf1}.list article:last-child{border:0}.list b,.list span,.list small{display:block}.list article>div>span,.metric small{font-size:11px;color:#8492a2;margin-top:4px}.metric{text-align:right;margin-right:20px}.metric span{font-family:monospace;color:#49647d}footer{text-align:center;color:#9aa5b1;font-size:11px;margin-top:24px}</style>
