<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
import type { FieldConfig, ResourceConfig } from '../config/resources'
import MonitorConfigFields from '../components/MonitorConfigFields.vue'
import TableActionButton from '../components/TableActionButton.vue'
const props=defineProps<{config:ResourceConfig}>(),rows=ref<any[]>([]),loading=ref(false),saving=ref(false),search=ref(''),dialog=ref(false),form=ref<any>({}),batchTesting=ref(false),testDialog=ref(false),testReport=ref<any>({results:[]}),relationOptions=ref<Record<string,any[]>>({})
const page=ref(1),pageSize=ref(20),total=ref(0)
let loadVersion=0
function searchRows(){page.value=1;load()}
const monitorConfigRef=ref<InstanceType<typeof MonitorConfigFields>>()
const deepCopy=<T>(value:T):T=>value==null?value:JSON.parse(JSON.stringify(value))
const display=(row:any,field:FieldConfig)=>field.key==='current_status'?({UP:'正常',DOWN:'故障',DEGRADED:'降级',PAUSED:'已暂停',MAINTENANCE:'维护中',PENDING:'待探测',UNKNOWN:'未知'} as any)[row[field.key]]||row[field.key]:field.type==='boolean'?(row[field.key]==null?'未探测':row[field.key]?'是':'否'):field.type==='datetime'&&row[field.key]?new Date(row[field.key]).toLocaleString():row[field.key]
async function load(){const version=++loadVersion;loading.value=true;try{const{data}=await client.get(`/${props.config.endpoint}/`,{params:{search:search.value,page:page.value,page_size:pageSize.value}});if(version!==loadVersion)return;rows.value=data.results||data;total.value=data.count??rows.value.length}catch(e:any){if(version===loadVersion)ElMessage.error(e.response?.data?.message||'加载失败')}finally{if(version===loadVersion)loading.value=false}}
async function loadRelations(){relationOptions.value={};for(const field of props.config.fields||[])if(field.type==='relation'&&field.endpoint&&!relationOptions.value[field.endpoint]){const{data}=await client.get(`/${field.endpoint}/`,{params:{page_size:200}});relationOptions.value[field.endpoint]=data.results||data}}
function fresh(){const value:any={};for(const field of props.config.fields||[]){const initial=field.default!==undefined?deepCopy(field.default):(field.multiple?[]:null);value[field.key]=field.type==='json'&&!(props.config.endpoint==='monitors'&&field.key==='config')?JSON.stringify(initial??{},null,2):initial}return value}
function openCreate(){form.value=fresh();dialog.value=true;loadRelations()}
function openEdit(row:any){form.value={...row,config:deepCopy(row.config||{})};for(const field of props.config.fields||[])if(field.type==='json'&&!(props.config.endpoint==='monitors'&&field.key==='config'))form.value[field.key]=JSON.stringify(row[field.key]??field.default??{},null,2);dialog.value=true;loadRelations()}
const labelOf=(item:any)=>item.name||item.username||item.code||item.number||item.id
const targetHints:Record<string,string>={HTTP:'完整 URL，例如：https://www.example.com/health',API:'完整接口 URL，例如：https://api.example.com/v1/health',TCP:'主机:端口，例如：10.0.0.8:8080',PING:'主机名或 IP，例如：192.168.1.10',DNS:'待解析域名，例如：www.example.com',SSL:'域名:端口，例如：www.example.com:443',MSSQL:'SQL Server 主机:端口，例如：10.0.0.10:1433',POSTGRESQL:'PostgreSQL 主机:端口，例如：10.0.0.11:5432',MYSQL:'MySQL/MariaDB 主机:端口，例如：10.0.0.12:3306',MONGODB:'MongoDB 主机:端口，例如：10.0.0.13:27017'}
const configHints:Record<string,string>={HTTP:'可配置 method、headers、params、expected_status、keywords、regex、follow_redirects',API:'支持请求头、查询参数、JSON/表单/文本请求体、响应断言，以及 bearer、basic、api_key、oauth2_client_credentials 认证',TCP:'可配置 send（发送内容）、expect（期望返回内容）',PING:'可配置 count（1-10）和 timeout',DNS:'可配置 record_type（A/AAAA/CNAME/MX/TXT）、server、expected',SSL:'可配置 warn_days（证书到期预警天数）',MSSQL:'必填 database、username、password；可选 query、expected_value、tds_version',POSTGRESQL:'必填 database、username、password；可选 query、expected_value、sslmode',MYSQL:'适用于 MySQL/MariaDB；必填 database、username、password；可选 query、expected_value、use_tls',MONGODB:'必填 database、username、password；可选 auth_source、use_tls'}
const configExamples:Record<string,string>={HTTP:'{\n  "method": "GET",\n  "expected_status": [200, 204],\n  "headers": {"Accept": "application/json"}\n}',API:'{\n  "method": "POST",\n  "auth": {"type": "bearer", "token": "请输入令牌"},\n  "json": {"ping": true},\n  "expected_status": [200, 201]\n}',TCP:'{\n  "send": "PING\\r\\n",\n  "expect": "PONG"\n}',PING:'{\n  "count": 3,\n  "timeout": 5\n}',DNS:'{\n  "record_type": "A",\n  "expected": ["1.2.3.4"]\n}',SSL:'{\n  "warn_days": 30\n}',MSSQL:'{\n  "database": "master",\n  "username": "monitor",\n  "password": "请输入密码",\n  "query": "SELECT 1",\n  "expected_value": 1\n}',POSTGRESQL:'{\n  "database": "postgres",\n  "username": "monitor",\n  "password": "请输入密码",\n  "sslmode": "prefer",\n  "query": "SELECT 1"\n}',MYSQL:'{\n  "database": "mysql",\n  "username": "monitor",\n  "password": "请输入密码",\n  "use_tls": false,\n  "query": "SELECT 1"\n}',MONGODB:'{\n  "database": "admin",\n  "username": "monitor",\n  "password": "请输入密码",\n  "auth_source": "admin",\n  "use_tls": false\n}'}
function fieldPlaceholder(field:FieldConfig){if(props.config.endpoint==='monitors'&&field.key==='target')return targetHints[form.value.monitor_type]||'';if(props.config.endpoint==='monitors'&&field.key==='config')return configExamples[form.value.monitor_type]||'{}';return field.placeholder||''}
function fieldHelp(field:FieldConfig){if(props.config.endpoint==='monitors'&&field.key==='config')return configHints[form.value.monitor_type]||'';return field.help||''}
async function save(){saving.value=true;try{if(props.config.endpoint==='monitors')form.value.config=monitorConfigRef.value?.normalize()||form.value.config;const payload={...form.value};for(const field of props.config.fields||[])if(field.type==='json'&&typeof payload[field.key]==='string')payload[field.key]=JSON.parse(payload[field.key]||'{}');payload.id?await client.patch(`/${props.config.endpoint}/${payload.id}/`,payload):await client.post(`/${props.config.endpoint}/`,payload);dialog.value=false;ElMessage.success('保存成功');await load()}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data?.details||e.response?.data||e.message||'保存失败'))}finally{saving.value=false}}
async function remove(row:any){try{await ElMessageBox.confirm(props.config.endpoint==='monitors'?'确认删除该探测任务？历史探测结果和故障事件将保留。':'确认删除该记录？此操作不可撤销。','删除确认',{type:'warning'});await client.delete(`/${props.config.endpoint}/${row.id}/`);if(rows.value.length===1&&page.value>1)page.value--;ElMessage.success(props.config.endpoint==='monitors'?'探测任务已删除，历史记录已保留':'删除成功');await load()}catch(e:any){if(e==='cancel'||e==='close')return;ElMessage.error(e.response?.data?.details?.detail||e.response?.data?.detail||'删除失败，请检查关联数据或权限')}}
async function action(row:any,name:string){try{const path=name==='test-channel'?'test':name,{data}=await client.post(`/${props.config.endpoint}/${row.id}/${path}/`);ElMessage.success(name==='test'?`探测完成：${data.success?'成功':'失败'}`:name==='rotate-token'?`新令牌：${data.token}`:'操作成功');load()}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data||'操作失败'))}}
async function testAll(){batchTesting.value=true;try{const{data}=await client.post(`/${props.config.endpoint}/test-all/`);testReport.value=data;testDialog.value=true;data.success?ElMessage.success(`全部测试通过（${data.passed}/${data.total}）`):ElMessage.warning(`测试完成：${data.failed} 项未通过`)}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data||'批量测试失败'))}finally{batchTesting.value=false}}
const actionLabel=(name:string)=>({test:'立即探测',acknowledge:'确认',close:'关闭','test-channel':'测试渠道','rotate-token':'轮换令牌'}[name]||name)
const actionIcon=(name:string):'run'|'check'|'close'|'refresh'=>name==='test'||name==='test-channel'?'run':name==='acknowledge'?'check':name==='close'?'close':'refresh'
watch(()=>props.config.endpoint,()=>{search.value='';page.value=1;rows.value=[];total.value=0;dialog.value=false;load()});onMounted(load);onBeforeUnmount(()=>{loadVersion++})
</script>
<template>
<div class="heading"><div><h2>{{config.title}}</h2><small>共 {{total}} 条记录</small></div><div class="toolbar"><el-input v-model="search" placeholder="搜索" clearable @clear="searchRows" @keyup.enter="searchRows"/><el-button @click="searchRows">查询</el-button><el-button v-if="config.endpoint==='monitors'||config.endpoint==='notification-channels'" :loading="batchTesting" @click="testAll">{{config.endpoint==='monitors'?'测试全部探测':'测试全部渠道'}}</el-button><el-button v-if="!config.readonly" type="primary" @click="openCreate">新增</el-button></div></div>
<el-card><el-table v-loading="loading" :data="rows" empty-text="暂无数据" stripe class="resource-table"><el-table-column v-for="column in config.columns" :key="column.key" :prop="column.key" :label="column.label" min-width="130" show-overflow-tooltip><template #default="scope"><el-tag v-if="column.type==='boolean'" :type="scope.row[column.key]?'success':'info'">{{display(scope.row,column)}}</el-tag><span v-else>{{display(scope.row,column)}}</span></template></el-table-column><el-table-column v-if="!config.readonly||(config.actions?.length)" label="操作" :width="config.readonly?Math.max(150,(config.actions?.length||0)*82+28):Math.max(150,(config.actions?.length||0)*88+132)" fixed="right" align="center"><template #default="scope"><div class="row-actions"><TableActionButton v-for="name in config.actions" :key="name" :icon="actionIcon(name)" :label="actionLabel(name)" tone="primary" @click="action(scope.row,name)"/><template v-if="!config.readonly"><TableActionButton icon="edit" label="编辑" tone="primary" @click="openEdit(scope.row)"/><TableActionButton icon="delete" label="删除" tone="danger" icon-only @click="remove(scope.row)"/></template></div></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" background @current-change="load" @size-change="searchRows"/></el-card>
<el-dialog v-model="dialog" :title="form.id?'编辑'+config.title:'新增'+config.title" :width="config.endpoint==='monitors'?'820px':'680px'"><el-form label-width="140px"><el-alert v-if="config.endpoint==='monitors'" :title="`${form.monitor_type||'HTTP'} 探测配置`" :description="targetHints[form.monitor_type]" type="info" :closable="false" class="monitor-hint"/><el-form-item v-for="field in config.fields" v-show="!(config.endpoint==='monitors'&&field.key==='config')" :key="field.key" :label="field.label" :required="field.required"><el-switch v-if="field.type==='boolean'" v-model="form[field.key]"/><el-input-number v-else-if="field.type==='number'" v-model="form[field.key]" :min="0" :placeholder="fieldPlaceholder(field)" style="width:100%"/><el-select v-else-if="field.type==='select'" v-model="form[field.key]" style="width:100%"><el-option v-for="option in field.options" :key="option" :label="option" :value="option"/></el-select><el-select v-else-if="field.type==='relation'" v-model="form[field.key]" :multiple="field.multiple" clearable filterable style="width:100%"><el-option v-for="item in relationOptions[field.endpoint||'']||[]" :key="item.id" :label="labelOf(item)" :value="item.id"/></el-select><el-date-picker v-else-if="field.type==='datetime'" v-model="form[field.key]" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width:100%"/><el-input v-else-if="field.type==='textarea'||field.type==='json'" v-model="form[field.key]" type="textarea" :rows="field.type==='json'?9:3" :placeholder="fieldPlaceholder(field)"/><el-input v-else v-model="form[field.key]" :placeholder="fieldPlaceholder(field)"/><small v-if="fieldHelp(field)" class="field-help">{{fieldHelp(field)}}</small></el-form-item><MonitorConfigFields v-if="config.endpoint==='monitors'" ref="monitorConfigRef" v-model="form.config" :type="form.monitor_type||'HTTP'"/></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
<el-dialog v-model="testDialog" :title="config.endpoint==='monitors'?'全部业务探测结果':'全部通知渠道测试结果'" width="860px"><div class="test-summary" :class="testReport.success?'passed':'failed'"><b>{{testReport.success?'全部通过':'存在未通过项目'}}</b><span>共 {{testReport.total}} 项，通过 {{testReport.passed}} 项，失败 {{testReport.failed}} 项</span></div><el-table :data="testReport.results" max-height="480"><el-table-column :label="config.endpoint==='monitors'?'业务 / 探测':'渠道'" min-width="190"><template #default="s"><b>{{s.row.business||s.row.name}}</b><small>{{s.row.monitor||s.row.type}}</small></template></el-table-column><el-table-column prop="type" label="类型" width="100"/><el-table-column label="结果" width="90"><template #default="s"><el-tag :type="s.row.success?'success':'danger'">{{s.row.success?'通过':'失败'}}</el-tag></template></el-table-column><el-table-column label="耗时" width="110"><template #default="s">{{s.row.latency_ms??'—'}} ms</template></el-table-column><el-table-column label="说明" min-width="240"><template #default="s">{{s.row.error_summary||s.row.message||(s.row.status_code?'HTTP '+s.row.status_code:'测试成功')}}</template></el-table-column></el-table><template #footer><el-button type="primary" @click="testDialog=false">完成</el-button></template></el-dialog>
</template>
<style scoped>.heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.heading h2{margin:0}.heading small{color:#8492a6}.toolbar{display:flex;gap:8px}.toolbar .el-input{width:230px}.resource-table :deep(.el-table__cell){padding:11px 0}.resource-table :deep(.el-table-fixed-column--right){background:#fff}.resource-table :deep(.el-table__row--striped .el-table-fixed-column--right){background:#fafafa}.row-actions{display:flex;align-items:center;justify-content:center;gap:6px;flex-wrap:nowrap;white-space:nowrap;padding:2px 4px;min-width:max-content}.row-actions :deep(.table-action){flex:0 0 auto}.test-summary{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;margin-bottom:14px;border-radius:6px}.test-summary.passed{color:#216b49;background:#eef9f3;border:1px solid #c7e7d5}.test-summary.failed{color:#9b3b3b;background:#fff4f4;border:1px solid #efd0d0}.test-summary span{font-size:12px}.el-table small{display:block;color:#8390a0;margin-top:4px}.monitor-hint{margin-bottom:18px}.field-help{display:block;width:100%;color:#8592a3;line-height:1.5;margin-top:5px}</style>
