<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
import TableActionButton from '../components/TableActionButton.vue'

const rows=ref<any[]>([]),catalog=ref<any[]>([]),loading=ref(false),dialog=ref(false),saving=ref(false),form=ref<any>({})
async function load(){loading.value=true;try{const requestTime=Date.now();const [roles,perms]=await Promise.all([client.get('/roles/',{params:{page_size:500,_t:requestTime}}),client.get('/roles/permission-catalog/',{params:{_t:requestTime}})]);rows.value=roles.data.results||roles.data;catalog.value=perms.data}catch(e:any){ElMessage.error(e.response?.data?.message||e.response?.data?.detail||'角色加载失败')}finally{loading.value=false}}
function add(){form.value={name:'',code:'',description:'',permissions:[],data_scope:'SELF',is_enabled:true};dialog.value=true}
function edit(row:any){form.value={...row,permissions:[...(row.permissions||[])]};dialog.value=true}
async function save(){if(!form.value.name||!form.value.code)return ElMessage.warning('请填写角色名称和编码');saving.value=true;try{const payload={...form.value};payload.id?await client.patch(`/roles/${payload.id}/`,payload):await client.post('/roles/',payload);dialog.value=false;ElMessage.success('角色权限保存成功');await load()}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data?.details||e.response?.data||'保存失败'))}finally{saving.value=false}}
async function remove(row:any){if(row.user_count)return ElMessage.warning('该角色仍有关联用户，请先解除关联');await ElMessageBox.confirm(`确定删除角色“${row.name}”吗？`,'删除角色',{type:'warning'});try{await client.delete(`/roles/${row.id}/`);ElMessage.success('角色已删除');load()}catch(e:any){ElMessage.error(e.response?.data?.detail||'删除失败')}}
const permissionCount=(r:any)=>(r.permissions||[]).length
const scopeLabel=(value:string)=>({ALL:'全部数据',DEPARTMENT:'本部门',SELF:'本人'} as Record<string,string>)[value]||value
onMounted(load)
</script>
<template><section><div class="page-head"><div><h2 class="page-title">角色管理</h2><div class="page-subtitle">通过角色分配功能权限和默认数据范围，权限由后端强制校验</div></div><el-button type="primary" @click="add">＋ 新增角色</el-button></div><el-card><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="name" label="角色名称" min-width="170"/><el-table-column prop="code" label="角色编码" width="160"/><el-table-column label="权限数" width="100"><template #default="s">{{permissionCount(s.row)}}</template></el-table-column><el-table-column prop="user_count" label="用户数" width="100"/><el-table-column label="数据范围" width="120"><template #default="s">{{scopeLabel(s.row.data_scope)}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.is_enabled?'success':'info'">{{s.row.is_enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="s"><div class="actions"><TableActionButton icon="edit" label="编辑" tone="primary" @click="edit(s.row)"/><TableActionButton icon="delete" label="删除" tone="danger" icon-only @click="remove(s.row)"/></div></template></el-table-column></el-table></el-card><el-dialog v-model="dialog" :title="form.id?'编辑角色':'新增角色'" width="720px"><el-form label-position="top"><div class="grid"><el-form-item label="角色名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="角色编码" required><el-input v-model="form.code" placeholder="如 OPS_ADMIN"/></el-form-item><el-form-item label="默认数据范围"><el-select v-model="form.data_scope" style="width:100%"><el-option label="全部数据" value="ALL"/><el-option label="本部门" value="DEPARTMENT"/><el-option label="本人" value="SELF"/></el-select></el-form-item><el-form-item label="启用角色"><el-switch v-model="form.is_enabled"/></el-form-item></div><el-form-item label="角色说明"><el-input v-model="form.description" type="textarea" :rows="2"/></el-form-item><div class="permission-title">功能权限</div><div class="permission-groups"><div v-for="group in catalog" :key="group.group" class="permission-group"><b>{{group.group}}</b><el-checkbox-group v-model="form.permissions"><el-checkbox v-for="item in group.items" :key="item[0]" :value="item[0]">{{item[1]}}</el-checkbox></el-checkbox-group></div></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存角色</el-button></template></el-dialog></section></template>
<style scoped>.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.actions{display:flex;gap:6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.permission-title{font-weight:700;margin:5px 0 10px}.permission-groups{border:1px solid #e1e7ee;border-radius:5px}.permission-group{display:grid;grid-template-columns:120px 1fr;padding:13px 16px}.permission-group+.permission-group{border-top:1px solid #e8edf2}.permission-group b{font-size:13px}.el-checkbox{min-width:180px}</style>
