<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import client from '../api/client'
const data=ref<any>({results:[],summary:{}}),days=ref(30),business=ref(''),businesses=ref<any[]>([]),loading=ref(false),exporting=ref(false)
async function load(){loading.value=true;try{data.value=(await client.get('/reports/sla/',{params:{days:days.value,business:business.value||undefined}})).data}catch{ElMessage.error('SLA 报表加载失败')}finally{loading.value=false}}
async function download(){exporting.value=true;try{const r=await client.get('/reports/sla/export.csv',{params:{days:days.value,business:business.value||undefined},responseType:'blob'});const url=URL.createObjectURL(r.data),a=document.createElement('a');a.href=url;a.download=`SLA报表-${days.value}天.csv`;a.click();URL.revokeObjectURL(url)}finally{exporting.value=false}}
onMounted(async()=>{const{data:r}=await client.get('/business-systems/',{params:{page_size:200,is_archived:false}});businesses.value=r.results||r;load()})
</script>
<template><div class="heading"><div><h2>SLA 报表</h2><p>按维护排除策略计算业务可用性和目标达成情况</p></div><div class="toolbar"><el-select v-model="business" clearable placeholder="全部业务" @change="load"><el-option v-for="x in businesses" :key="x.id" :label="x.name" :value="x.id"/></el-select><el-select v-model="days" @change="load"><el-option :value="1" label="最近 1 天"/><el-option :value="7" label="最近 7 天"/><el-option :value="30" label="最近 30 天"/><el-option :value="90" label="最近 90 天"/><el-option :value="365" label="最近 365 天"/></el-select><el-button :loading="exporting" @click="download">导出 CSV</el-button></div></div>
<div class="summary"><div><b>{{data.summary.monitors||0}}</b><span>统计探测任务</span></div><div class="good"><b>{{data.summary.availability==null?'—':data.summary.availability+'%'}}</b><span>综合可用率</span></div><div><b>{{data.summary.targets_met||0}}</b><span>达到 SLA 目标</span></div><div><b>{{data.summary.included_samples||0}}</b><span>纳入统计样本</span></div><div><b>{{data.summary.excluded_samples||0}}</b><span>维护排除样本</span></div></div>
<el-alert :title="data.formula" :description="`报表生成时间：${data.generated_at?new Date(data.generated_at).toLocaleString():'—'}`" type="info" :closable="false"/>
<el-card shadow="never" class="table"><el-table v-loading="loading" :data="data.results" stripe><el-table-column prop="business_name" label="业务系统" min-width="170"/><el-table-column prop="monitor_name" label="探测任务" min-width="190"/><el-table-column label="SLA 目标" width="110"><template #default="s">{{s.row.sla_target}}%</template></el-table-column><el-table-column label="实际可用率" width="130"><template #default="s"><b :class="s.row.target_met?'pass':'fail'">{{s.row.availability==null?'无数据':s.row.availability+'%'}}</b></template></el-table-column><el-table-column label="达标" width="90"><template #default="s"><el-tag :type="s.row.target_met===true?'success':s.row.target_met===false?'danger':'info'">{{s.row.target_met===true?'达标':s.row.target_met===false?'未达标':'无数据'}}</el-tag></template></el-table-column><el-table-column prop="samples" label="纳入样本" width="100"/><el-table-column prop="excluded_samples" label="维护排除" width="100"/><el-table-column label="平均响应" width="130"><template #default="s">{{s.row.average_latency_ms==null?'—':Number(s.row.average_latency_ms).toFixed(2)+' ms'}}</template></el-table-column></el-table></el-card></template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:end;margin-bottom:15px}.heading h2{margin:0}.heading p{margin:5px 0 0;color:#7c8b9d}.toolbar{display:flex;gap:8px}.toolbar .el-select:first-child{width:190px}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:14px}.summary>div{background:#fff;border:1px solid #dfe6ed;border-top:3px solid #397fa8;padding:15px;border-radius:6px}.summary .good{border-top-color:#36a36c}.summary b,.summary span{display:block}.summary b{font-size:23px}.summary span{font-size:12px;color:#8190a2;margin-top:5px}.table{margin-top:14px}.pass{color:#268057}.fail{color:#c44d4d}</style>
