<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
const rows=ref<any[]>([]),dialog=ref(false),saving=ref(false),form=ref<any>({}),businesses=ref<any[]>([]),monitors=ref<any[]>([])
async function load(){const{data}=await client.get('/status-pages/',{params:{page_size:100}});rows.value=data.results||data}
async function options(){const[b,m]=await Promise.all([client.get('/business-systems/',{params:{page_size:200,is_archived:false}}),client.get('/monitors/',{params:{page_size:200}})]);businesses.value=b.data.results||b.data;monitors.value=m.data.results||m.data}
async function open(row?:any){form.value=row?{...row}:{name:'',slug:'',description:'',access_mode:'PUBLIC',theme_color:'#0c6c79',businesses:[],monitors:[],is_enabled:true};dialog.value=true;options()}
async function save(){saving.value=true;try{form.value.id?await client.patch(`/status-pages/${form.value.id}/`,form.value):await client.post('/status-pages/',form.value);ElMessage.success('状态页已保存');dialog.value=false;load()}catch(e:any){ElMessage.error(JSON.stringify(e.response?.data?.details||e.response?.data||'保存失败'))}finally{saving.value=false}}
async function rotate(row:any){await ElMessageBox.confirm('旧令牌将立即失效，确认继续？','轮换访问令牌',{type:'warning'});const{data}=await client.post(`/status-pages/${row.id}/rotate-token/`);await navigator.clipboard.writeText(`${location.origin}/status/${row.slug}?token=${data.token}`);ElMessage.success('新访问链接已复制；令牌仅显示本次')}
async function remove(row:any){await ElMessageBox.confirm(`确认删除“${row.name}”？`,'删除状态页',{type:'warning'});await client.delete(`/status-pages/${row.id}/`);load()}
const visit=(row:any)=>window.open(`/status/${row.slug}`,'_blank')
onMounted(load)
</script>
<template><div class="heading"><div><h2>状态页</h2><p>面向业务方发布脱敏后的实时服务可用状态</p></div><el-button type="primary" @click="open()">新增状态页</el-button></div><el-card shadow="never"><el-table :data="rows" stripe><el-table-column label="状态页" min-width="220"><template #default="s"><b>{{s.row.name}}</b><small>/status/{{s.row.slug}}</small></template></el-table-column><el-table-column label="访问方式" width="130"><template #default="s"><el-tag :type="s.row.access_mode==='PUBLIC'?'success':'warning'">{{s.row.access_mode==='PUBLIC'?'公开访问':'令牌访问'}}</el-tag></template></el-table-column><el-table-column prop="monitor_count" label="展示探测" width="110"/><el-table-column label="业务范围" min-width="210"><template #default="s">{{s.row.business_names?.join('、')||s.row.monitor_names?.join('、')||'—'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.is_enabled?'success':'info'">{{s.row.is_enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="260"><template #default="s"><el-button link type="primary" @click="visit(s.row)">预览</el-button><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button v-if="s.row.access_mode==='TOKEN'" link type="warning" @click="rotate(s.row)">轮换令牌</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table></el-card>
<el-dialog v-model="dialog" :title="form.id?'编辑状态页':'新增状态页'" width="700px"><el-form label-width="120px"><el-form-item label="名称" required><el-input v-model="form.name" placeholder="例如：核心业务服务状态"/></el-form-item><el-form-item label="访问标识" required><el-input v-model="form.slug" placeholder="例如：core-services"/></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="访问方式"><el-radio-group v-model="form.access_mode"><el-radio value="PUBLIC">公开访问</el-radio><el-radio value="TOKEN">令牌访问</el-radio></el-radio-group></el-form-item><el-form-item label="主题色"><el-color-picker v-model="form.theme_color"/><span class="color">{{form.theme_color}}</span></el-form-item><el-form-item label="业务系统"><el-select v-model="form.businesses" multiple filterable clearable style="width:100%"><el-option v-for="x in businesses" :key="x.id" :label="x.name" :value="x.id"/></el-select><small>自动展示所选业务下全部探测任务</small></el-form-item><el-form-item label="补充探测任务"><el-select v-model="form.monitors" multiple filterable clearable style="width:100%"><el-option v-for="x in monitors" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item><el-form-item label="启用"><el-switch v-model="form.is_enabled"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:end;margin-bottom:16px}.heading h2{margin:0}.heading p{margin:5px 0 0;color:#7e8d9f}small{display:block;color:#8391a2;margin-top:4px}.color{margin-left:10px;color:#718195}</style>
