<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import client from '../api/client'
const data=ref<any>({components:{},statistics:{},permissions:{}}),loading=ref(false),running=ref('')
const names:any={database:'PostgreSQL 数据库',redis:'Redis 缓存',task_queue:'Celery 任务队列',scheduler:'探测调度器'}
const fmt=(v:string)=>v?new Date(v).toLocaleString():'—'
async function load(){loading.value=true;try{data.value=(await client.get('/system/overview/')).data}catch(e:any){ElMessage.error(e.response?.data?.message||'系统状态加载失败')}finally{loading.value=false}}
async function maintain(operation:string,label:string){await ElMessageBox.confirm(`确认执行“${label}”？任务将在后台安全执行。`,'系统维护',{type:'warning'});running.value=operation;try{const{data:r}=await client.post('/system/maintenance/',{operation});ElMessage.success(`已提交，队列任务 ${r.queued} 个`);await load()}catch(e:any){ElMessage.error(e.response?.data?.details?.operation||e.response?.data?.message||'操作失败')}finally{running.value=''}}
onMounted(load)
</script>
<template>
<div class="heading"><div><h2>系统健康</h2><p>基础组件、业务运行指标与数据维护</p></div><el-button :loading="loading" @click="load">重新检查</el-button></div>
<div class="hero" :class="data.status"><div><span class="pulse"></span><div><b>{{data.status==='ok'?'系统运行正常':'系统存在需关注项'}}</b><small>检查时间 {{fmt(data.checked_at)}} · 版本 {{data.environment||'—'}}</small></div></div><el-tag :type="data.status==='ok'?'success':'warning'">{{data.status==='ok'?'全部就绪':'需要检查'}}</el-tag></div>
<div class="stats"><div><b>{{data.statistics?.active_monitors||0}}</b><span>有效探测任务</span></div><div><b>{{data.statistics?.open_incidents||0}}</b><span>开放故障事件</span></div><div :class="{danger:data.statistics?.failed_notifications}"><b>{{data.statistics?.failed_notifications||0}}</b><span>失败通知</span></div><div><b>{{data.statistics?.monitor_results||0}}</b><span>探测结果记录</span></div><div><b>{{data.statistics?.users||0}}</b><span>有效用户</span></div><div><b>{{data.statistics?.audit_logs||0}}</b><span>审计记录</span></div></div>
<el-card shadow="never" class="section"><template #header><div class="title"><b>基础组件</b><span>真实连接检测与运行活跃度</span></div></template><div class="components"><div v-for="(item,key) in data.components" :key="key" class="component"><i :class="item.status"></i><div><b>{{names[key]||key}}</b><small>{{item.message||((item.latency_ms!=null)?`连接延迟 ${item.latency_ms} ms`:'运行正常')}}</small></div><el-tag :type="item.status==='ok'?'success':item.status==='warning'?'warning':'danger'">{{item.status==='ok'?'正常':item.status==='warning'?'需关注':'异常'}}</el-tag><em v-if="item.pending!=null">待处理 {{item.pending}}</em><em v-if="item.last_probe_at">{{fmt(item.last_probe_at)}}</em></div></div></el-card>
<el-card shadow="never" class="section"><template #header><div class="title"><b>系统维护</b><span>所有操作异步执行并写入审计日志</span></div></template><el-alert v-if="!data.permissions?.can_manage" title="当前账号只有查看权限，维护操作需要“系统维护”权限" type="info" :closable="false"/><div v-else class="maintenance"><div><b>探测结果保留策略</b><span>全局仅保留最新 {{data.retention?.monitor_results||10000}} 条，清理关联状态迁移</span><el-button :loading="running==='cleanup_results'" @click="maintain('cleanup_results','清理超限探测结果')">立即清理</el-button></div><div><b>通知补偿扫描</b><span>补偿开放事件遗漏的故障及持续通知</span><el-button :loading="running==='reconcile_notifications'" @click="maintain('reconcile_notifications','执行通知补偿扫描')">执行扫描</el-button></div><div><b>失败通知重试</b><span>将最近最多 500 条失败通知重新加入发送队列</span><el-button type="danger" plain :disabled="!data.statistics?.failed_notifications" :loading="running==='retry_failed_notifications'" @click="maintain('retry_failed_notifications','重试失败通知')">批量重试</el-button></div></div></el-card>
</template>
<style scoped>.heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.heading h2{margin:0;color:#192c42}.heading p{margin:5px 0 0;color:#7b8a9c}.hero{display:flex;align-items:center;justify-content:space-between;padding:20px 24px;color:#fff;border-radius:8px;background:linear-gradient(115deg,#314c68,#42627d);box-shadow:0 8px 22px #1736531c}.hero.ok{background:linear-gradient(115deg,#124e64,#167563)}.hero>div{display:flex;align-items:center;gap:14px}.hero b,.hero small{display:block}.hero b{font-size:19px}.hero small{color:#c4dce3;margin-top:5px}.pulse{width:13px;height:13px;border-radius:50%;background:#77edbd;box-shadow:0 0 0 7px #70ddb52e}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:15px 0}.stats>div{background:#fff;border:1px solid #dfe6ed;border-top:3px solid #3382ad;border-radius:7px;padding:15px 17px}.stats b,.stats span{display:block}.stats b{font-size:25px;color:#21364d}.stats span{font-size:12px;color:#8190a1;margin-top:5px}.stats .danger{border-top-color:#d85b5b}.stats .danger b{color:#bd4141}.section{margin-bottom:14px}.title{display:flex;align-items:end;gap:12px}.title span{font-size:12px;color:#8593a3}.components{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.component{display:grid;grid-template-columns:12px 1fr auto;align-items:center;gap:12px;padding:15px;border:1px solid #e1e7ed;border-radius:6px}.component i{width:9px;height:9px;border-radius:50%;background:#df5555}.component i.ok{background:#34a66c;box-shadow:0 0 0 4px #34a66c1f}.component i.warning{background:#e4a53c}.component b,.component small{display:block}.component small{color:#8492a3;margin-top:4px}.component em{grid-column:2/4;color:#6f8193;font-size:11px;font-style:normal}.maintenance{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.maintenance>div{display:grid;grid-template-rows:auto 1fr auto;padding:17px;border:1px solid #e0e7ed;border-radius:7px}.maintenance span{font-size:12px;color:#7d8c9e;line-height:1.6;margin:7px 0 14px}.maintenance .el-button{justify-self:start}@media(max-width:1100px){.stats{grid-template-columns:repeat(3,1fr)}.components,.maintenance{grid-template-columns:1fr}}</style>
